language: python
sudo: false
python: 2.7
services:
    - mysql
env:
    global:
        - DB_HOST=localhost
        - DB_MYSQL_USER=travis
        - DB_PASSWORD=''
        - PYTHONPATH=$PWD/coda
before_script:
    - mysql -e 'create database coda_local;'
    - cp secrets.json.template secrets.json
script:
    - py.test --create-db
    - flake8
