# Generated by Django 2.2.16 on 2020-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda_mdstore', '0001_squashed_0003_auto_20191022_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive')], help_text='The current status of the node', max_length=10),
        ),
    ]
