# Generated by Django 2.2.16 on 2020-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda_mdstore', '0001_squashed_0003_auto_20191022_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Inactive'), ('1', 'Active')], help_text='The current status of the node', max_length=1),
        ),
    ]
