# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda_mdstore', '0002_add_fulltext_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bagging_date',
            field=models.DateField(help_text='Date of Bag Creation'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bagit_version',
            field=models.CharField(help_text='BagIt version number', max_length=10),
        ),
        migrations.AlterField(
            model_name='bag',
            name='files',
            field=models.IntegerField(help_text='Number of files in Bag'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='last_verified_date',
            field=models.DateField(help_text='Date of last Bag Verification'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='last_verified_status',
            field=models.CharField(help_text='Status of last bag Verification', max_length=25),
        ),
        migrations.AlterField(
            model_name='bag',
            name='name',
            field=models.CharField(help_text='Name of Bag', max_length=255, primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.BigIntegerField(help_text="Size of Bag's Payload (in bytes)"),
        ),
        migrations.AlterField(
            model_name='bag_info',
            name='field_body',
            field=models.TextField(help_text='Field Body'),
        ),
        migrations.AlterField(
            model_name='bag_info',
            name='field_name',
            field=models.CharField(db_index=True, help_text='Field Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='Date node size last checked'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_capacity',
            field=models.BigIntegerField(blank=True,
                                         help_text='The total amount of storage (in bytes)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_name',
            field=models.CharField(db_index=True, help_text='The name of the node',
                                   max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_path',
            field=models.CharField(help_text="The path on disk to the node's root",
                                   max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_size',
            field=models.BigIntegerField(blank=True,
                                         help_text='The current size of files on disk (in bytes)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_url',
            field=models.TextField(help_text='The external url for the root of the node'),
        ),
    ]
