# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-29 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coda_replication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'verbose_name_plural': 'queue entries'},
        ),
    ]
