# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda_validate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validate',
            name='last_verified_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Unverified', max_length=25),
        ),
    ]
