name: Test coda

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    services:
      mariadb:
        image: mariadb:10.3
        ports: 
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: 'root'
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: coda_local
          MYSQL_HOST: localhost
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
          cp secrets.json.template secrets.json
      - name: Lint with flake8
        run: |
          # Python syntax errors or undefined names will stop the build completely.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero will still allow the tests to pass, with these types of errors as warnings.
          # flake8 coda --count --exit-zero --max-line-length=99 --statistics
      - name: Run the tests
        run: |
            pytest --create-db